feat: add results and page metadata to filter bar
metrotranscom/doorway pull request #769
Opened 2024-07-31 03:10 UTC by jaredcwhite

This PR addresses #(insert-number-here)

- [ ] Addresses the issue in full
- [ ] Addresses only certain aspects of the issue

## Description

Please include a summary of the change and which issue(s) is addressed.

## How Can This Be Tested/Reviewed?

Provide instructions so we can review, including any needed configuration, and the test cases that need to be QAd.

## Author Checklist:

- [ ] Added QA notes to the issue with applicable URLs
- [ ] Reviewed in a desktop view
- [ ] Reviewed in a mobile view
- [ ] Reviewed considering accessibility
- [ ] Added tests covering the changes
- [ ] Made corresponding changes to the documentation
- [ ] Ran `yarn generate:client` and/or created a migration when required

## Review Process:

- Read and understand the issue
- Ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't need to re-review after the updates

2024-08-08 18:13 UTC, emilyjablonski requested changes
![Screenshot 2024-08-08 at 12 07 49 PM](https://github.com/user-attachments/assets/a6417e96-28b4-4406-803b-add33cc46bb0)
![Screenshot 2024-08-08 at 12 07 45 PM](https://github.com/user-attachments/assets/a00f4e57-e1cc-4f29-b575-17e1378c70e0)
![Screenshot 2024-08-08 at 12 07 31 PM](https://github.com/user-attachments/assets/364295d7-67c0-461a-a4d7-63d5a48eaa93)
![Screenshot 2024-08-08 at 12 07 23 PM](https://github.com/user-attachments/assets/f2fc9421-3fa6-4fcb-ba29-bc966e3acf86)

2024-08-08 18:26 UTC, emilyjablonski commented on sites/public/src/components/listings/ListingsCombined.module.scss
> +  --padding: 2.5rem;
`--seeds-s10`

2024-08-08 18:27 UTC, emilyjablonski commented on sites/public/src/components/listings/search/ListingsSearch.module.scss
> +  --swipe-area-height: var(--bloom-s14);
`--seeds-s14`

2024-08-08 18:27 UTC, emilyjablonski commented on sites/public/src/components/listings/search/ListingsSearch.module.scss
> +  --background-color: var(--bloom-color-white);
`--seeds-bg-color-surface`

2024-08-08 18:43 UTC, emilyjablonski commented
![Screenshot 2024-08-08 at 12 43 06 PM](https://github.com/user-attachments/assets/2b34e80c-c3ce-4129-964f-6d5c70f77bf6)
We're also showing 1 of 0 in an empty state

2024-08-12 23:33 UTC, jaredcwhite commented
Thanks @emilyjablonski for the feedback! I'll work on making changes.

2024-08-13 20:59 UTC, jaredcwhite commented
@emilyjablonski I think it has been tightened up now. One change I didn't make was that I kept the text button color intact on mobile. I'm not sure why in the Figma the button shows the same dark gray text color as regular text. We can ask design, but that seems out of step with the design system to me.

I also noticed some horizontal padding issues with some other content in the sidebar, but that was present before this ticket. We can decide if we want to address that here or separately.

2024-08-16 19:25 UTC, jaredcwhite commented
Thanks @emilyjablonski for the additional review! I think we're OK regarding the Total Results font size – I took screenshots of the page and the Figma design and compared the sizes and it's looking identical (at least on my machine in Safari).

2024-08-16 19:26 UTC, merged