fix: base styling + functionality
metrotranscom/doorway pull request #990
Opened 2024-12-10 19:04 UTC by ColinBuyck

This PR addresses #(insert-number-here)

- [ ] Addresses the issue in full
- [ ] Addresses only certain aspects of the issue

## Description

Please include a summary of the change and which issue(s) is addressed.

## How Can This Be Tested/Reviewed?

Provide instructions so we can review, including any needed configuration, and the test cases that need to be QAd.

## Author Checklist:

- [ ] Added QA notes to the issue with applicable URLs
- [ ] Reviewed in a desktop view
- [ ] Reviewed in a mobile view
- [ ] Reviewed considering accessibility
- [ ] Added tests covering the changes
- [ ] Made corresponding changes to the documentation
- [ ] Ran `yarn generate:client` and/or created a migration when required

## Review Process:

- Read and understand the issue
- Ensure the author has added QA notes
- Review the code itself from a style point of view
- Pull the changes down locally and test that the acceptance criteria is met
- Either (1) explicitly ask a clarifying question, (2) request changes, or (3) approve the PR, even if there are very small remaining changes, if you don't need to re-review after the updates

2025-01-13 05:54 UTC, ColinBuyck commented on sites/public/src/components/listings/search/ListingsSearchModal.tsx
**thought:** Not my proudest moment but given the css chaos between ListingsSearchModal and LandingSearch files, I figured it was best to follow existing patterns since I don't have space to refactor it all.

2025-01-14 00:56 UTC, ColinBuyck commented on sites/public/src/components/listings/search/LandingSearch.tsx
> +    // handle semicolon by searching text before since removing could lead to missing exact match
**thought:** To expand on this, "Homes; Boutique" would not match "Homes Boutique" if we were to filter out the semicolon so searching on the first piece seemed like a reasonable workaround rather than rethinking our url building pattern

2025-01-14 00:58 UTC, ColinBuyck commented on sites/public/src/components/listings/search/ListingsSearchModal.tsx
> +  padding: "0.5rem .7rem",
**note:** This styling seemed pretty arbitrary and was making the spacing irregular. Now, the 0.5 rem vertical padding matches the margin on the field adjacent field component

2025-01-14 00:59 UTC, ColinBuyck commented on sites/public/src/lib/listings/search.ts
> +    // Handle colon as possible input for text fields
**question:** Does this one off seem worth it to include the whole search term? Alternatively, I thought of handling colons like semicolons and only using the first portion of the search to match

2025-01-15 22:24 UTC, emilyjablonski commented on shared-helpers/src/locales/general.json
> +  "listings.popertyName.helper": "Enter full or partial property name",
**nitpick (non-blocking):** `popertyName` --> `propertyName`

2025-01-15 22:27 UTC, emilyjablonski commented on sites/public/src/lib/listings/search.ts
> +    // Handle colon as possible input for text fields
suggestion(nb): could we for both cases remove the character and replace it with a space? in know it still may not match, but we would be including everything else the user entered

2025-01-15 22:30 UTC, emilyjablonski requested changes
This functionally looks great - there is one small bug around the clear filters button in the modal. To be fair, I kind of wonder if the button should clear the filter, submit it, and auto close the modal, but with the current pattern the input field should clear (video in Slack, github is being upsetty spaghetti).

We also do need to make sure all the data is sanitized, but I remember @YazeedLoonat mentioning at some point that Prisma gives us some of that for free. Just wanna confirm w him!

2025-01-15 22:50 UTC, ColinBuyck commented on sites/public/src/lib/listings/search.ts
> +    // Handle colon as possible input for text fields
Good question! Tossed and turned on this and am just struggling to see the benefit of including everything else the user entered when the space would guarantee a mismatch with the exactly typed out match. Like for this example https://github.com/metrotranscom/doorway/pull/990#discussion_r1913982271. What do you think? To your point though, the user would then open up the search modal and see half of their search... which is also pretty confusing.  I briefly explored custom encoding that one character if you think that would be worth it?

2025-01-15 22:51 UTC, ColinBuyck commented on shared-helpers/src/locales/general.json
> +  "listings.popertyName.helper": "Enter full or partial property name",
Embarassinggggg (good catch 🐧 )

2025-01-15 23:02 UTC, ColinBuyck commented
@emilyjablonski Thanks for the thorough review! I fixed that clear filters and spelling bugs and left some thoughts on the other comment 🛸

2025-01-16 00:27 UTC, emilyjablonski commented on sites/public/src/lib/listings/search.ts
> +    // Handle colon as possible input for text fields
oh i think that's a fabulous point! (that maybe we could get a partial match if we just shortcut it) - w the limitations of the flexibility of our search, makes a lot of sense as it is now 🫡

2025-01-16 00:28 UTC, emilyjablonski approved these changes
Wanna confirm the santiziation w Yazeed otherwise lgtm!

2025-01-16 16:29 UTC, mcgarrye approved these changes
WOOOO

2025-01-16 16:47 UTC, YazeedLoonat requested changes
@emilyjablonski @mcgarrye @ColinBuyck I think the way the search was implemented here leaves us vulnerable to sql injection 

specifically I think the way we are sanitizing the string isn't quite strong enough and leaves room for people to inject deletes or updates or whatever. 

I don't have an immediate "do this instead" but peeping what prisma offers: https://www.prisma.io/docs/orm/prisma-client/type-safety/prisma-validator 

you could possibly use that, but this may need a bit more investigation into how to properly sanitize that if the prisma validator fails us

_edit_: further reading seems to be: https://www.prisma.io/docs/orm/prisma-client/using-raw-sql/raw-queries

2025-01-23 01:45 UTC, ColinBuyck commented
@YazeedLoonat I've updated the listing service to handle having multiple search filters as we discussed. I did want to flag that the sites/public search.ts file does not allow for this even if you manually add multiple searches via the url params. It stores the search value with the filter name as the key on the object.

As for parameterizing the whole query, I decided to wait on this since due to this [post](https://stackoverflow.com/questions/73298476/parametrized-raw-sql-queries-on-prisma-with-in-are-causing-invalid-prisma-quer/73298789#73298789). It seems this would only be possible to do with switching the counties where clause to ANY rather than IN. Given the sensitivity of this query with the map along with the original issue being frontend focused that work is captured in https://github.com/metrotranscom/doorway/issues/1058

2025-01-23 18:16 UTC, YazeedLoonat approved these changes
LGTM 🫶

2025-01-23 18:34 UTC, merged